import React from 'react';
import {
  LayoutGrid,
  Sparkles,
  Clock,
  MapPin,
  List,
  Trash2,
  X,
  Heart,
  Pencil,
  Share2,
  Info,
  ChevronLeft,
  ChevronRight,
  BarChart3,
  Settings,
  Search,
  Play,
  Pause,
  Folder,
  ImageIcon,
  Camera,
  Bot,
  Palette,
  Box,
  Columns2,
  Check,
  Plus,
  ImagePlus,
  Scan,
  Leaf,
  User,
  EyeOff,
  CheckCircle,
  Cloud,
  Shield,
  MoreHorizontal,
  Menu,
  CircleDot,
  History,
  Lock,
  Star,
  Pin,
  Edit3,
  ArrowLeftRight,
  ClipboardList,
  SortAsc,
  Type,
  Hash,
  FolderOpen,
  Sliders,
  Paintbrush,
  Crop,
  PenTool,
  Download,
  FileImage,
  FileJson,
  FileArchive,
  AlertCircle,
  Users,
  Map,
  Tag,
  HardDrive,
  FileText,
  Eye,
  Fingerprint,
  Sun,
  Moon,
  Bell,
  Link,
  Wifi,
  WifiOff,
  RefreshCw,
  ArrowUpRight,
  ChevronDown,
  ChevronUp,
  ArrowLeft,
  ArrowRight,
  ExternalLink,
  Copy,
  ZoomIn,
  ZoomOut,
  RotateCcw,
  RotateCw,
  Maximize2,
  Minimize2,
  Move,
  Grid2x2,
  Grid3x3,
  Filter,
  SlidersHorizontal,
  Image,
  Video,
  Film,
  Music,
  Mic,
  Volume2,
  VolumeX,
  Phone,
  Mail,
  MessageSquare,
  Calendar,
  Clock4,
  Timer,
  Globe,
  Compass,
  Navigation,
  MapPinned,
  Locate,
  Crosshair,
  Target,
  Zap,
  Flame,
  Droplets,
  Wind,
  Snowflake,
  Umbrella,
  Thermometer,
  Sunrise,
  Sunset,
  CloudRain,
  CloudSnow,
  CloudLightning,
  CloudDrizzle,
  CloudFog,
  CloudOff,
  CloudSun,
  CloudMoon,
  Mountain,
  Cat,
  Utensils,
  Flower2,
} from 'lucide-react-native';

interface LineIconProps {
  name: string;
  size?: number;
  color?: string;
  style?: any;
  fill?: string;
}

const ICON_MAP: Record<string, React.ComponentType<any>> = {
  grid: LayoutGrid,
  'grid-filled': LayoutGrid,
  sparkle: Sparkles,
  'sparkle-filled': Sparkles,
  sparkles: Sparkles,
  clock: Clock,
  'clock-filled': Clock,
  'map-pin': MapPin,
  'map-pin-filled': MapPin,
  list: List,
  'list-filled': List,
  trash: Trash2,
  'trash-filled': Trash2,
  close: X,
  heart: Heart,
  'heart-filled': Heart,
  pencil: Pencil,
  share: Share2,
  info: Info,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'bar-chart': BarChart3,
  settings: Settings,
  search: Search,
  'search-filled': Search,
  play: Play,
  pause: Pause,
  folder: Folder,
  'folder-filled': Folder,
  image: ImageIcon,
  camera: Camera,
  robot: Bot,
  palette: Palette,
  box: Box,
  compare: Columns2,
  check: Check,
  plus: Plus,
  photo: ImagePlus,
  'photo-filled': ImagePlus,
  scan: Scan,
  leaf: Leaf,
  user: User,
  'user-filled': User,
  'eye-off': EyeOff,
  'check-circle': CheckCircle,
  cloud: Cloud,
  shield: Shield,
  more: MoreHorizontal,
  menu: Menu,
  'live-photo': CircleDot,
  'live-photo-filled': CircleDot,
  'clock-arrow': History,
  lock: Lock,
  star: Star,
  pin: Pin,
  edit: Edit3,
  'arrow-left-right': ArrowLeftRight,
  exif: ClipboardList,
  'sort-recent': SortAsc,
  'sort-name': Type,
  'sort-count': Hash,
  'sort-type': FolderOpen,
  adjust: Sliders,
  filter: Paintbrush,
  crop: Crop,
  draw: PenTool,
  download: Download,
  'file-image': FileImage,
  'file-json': FileJson,
  'file-archive': FileArchive,
  alert: AlertCircle,
  users: Users,
  map: Map,
  tag: Tag,
  storage: HardDrive,
  'file-text': FileText,
  eye: Eye,
  fingerprint: Fingerprint,
  sun: Sun,
  moon: Moon,
  bell: Bell,
  link: Link,
  wifi: Wifi,
  'wifi-off': WifiOff,
  refresh: RefreshCw,
  'arrow-up-right': ArrowUpRight,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'external-link': ExternalLink,
  copy: Copy,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  maximize: Maximize2,
  minimize: Minimize2,
  move: Move,
  'grid-2x2': Grid2x2,
  'grid-3x3': Grid3x3,
  'filter-icon': Filter,
  'sliders': SlidersHorizontal,
  video: Video,
  film: Film,
  music: Music,
  mic: Mic,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  phone: Phone,
  mail: Mail,
  message: MessageSquare,
  calendar: Calendar,
  'clock-4': Clock4,
  timer: Timer,
  stopwatch: Timer,
  globe: Globe,
  compass: Compass,
  navigation: Navigation,
  'map-pinned': MapPinned,
  locate: Locate,
  crosshair: Crosshair,
  target: Target,
  zap: Zap,
  flame: Flame,
  droplets: Droplets,
  wind: Wind,
  snowflake: Snowflake,
  umbrella: Umbrella,
  thermometer: Thermometer,
  sunrise: Sunrise,
  sunset: Sunset,
  'cloud-rain': CloudRain,
  'cloud-snow': CloudSnow,
  'cloud-lightning': CloudLightning,
  'cloud-drizzle': CloudDrizzle,
  'cloud-fog': CloudFog,
  'cloud-off': CloudOff,
  'cloud-sun': CloudSun,
  'cloud-moon': CloudMoon,
  mountain: Mountain,
  cat: Cat,
  utensils: Utensils,
  'flower-2': Flower2,
};

const FILLED_ICONS = new Set([
  'grid-filled',
  'sparkle-filled',
  'clock-filled',
  'map-pin-filled',
  'list-filled',
  'trash-filled',
  'heart-filled',
  'search-filled',
  'folder-filled',
  'photo-filled',
  'live-photo-filled',
  'user-filled',
]);

export function LineIcon({ name, size = 24, color = '#49454F', style, fill }: LineIconProps) {
  const IconComponent = ICON_MAP[name];

  if (!IconComponent) {
    return null;
  }

  const isFilled = FILLED_ICONS.has(name);
  const iconFill = fill ?? (isFilled ? color : 'none');

  return (
    <IconComponent
      size={size}
      color={color}
      fill={iconFill}
      strokeWidth={isFilled ? 0 : 2}
      style={style}
    />
  );
}
